version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: dotnet test src/tests/DotNetGraphQLQueryGen.Tests/